style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/ldelossa/gcl
options:
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Scope
  header:
    pattern: '^(.*):\s*(.*)$'
    pattern_maps:
      - Scope
      - Subject
  issues:
    prefix: 
      - "#"
  refs:
    actions:
      - Closes
      - Fixes
  notes:
    keywords:
      - BREAKING CHANGE
      - Note
