---
name: CI

on: [push, pull_request]

jobs:
  commit-check:
    name: commit check
    runs-on: ubuntu-latest
    steps:
      - name: commit check
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: |
            ^(.*):\s*(.*)$          
          flags: 'gm'
          error: 'Commit must begin with <scope>: <subject>'
