---
name: Prepare Release
# Prepare Release looks for a tag with a "prepare" prefix.
# If encountered an automated changelog pull request will be opened against the repository.
# If the tag does not contain alpha, beta, or rc test artifacts will be created for QE testing.

on:
  push:
    tags:
      - prepare-*

jobs:
  prepare:
    name: Prepare Release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Setup
        run: |
          tag=`basename github.ref`
          echo $tag | grep -E "alpha|beta|rc"
          is_prod_releaes = $?
          cat <<.
          ::set-env name=VERSION::${tag}
          ::set-env name=PROD_RELEASE::%{is_prod_release}
          .
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        # A tag that triggers this workflow should only exist on one branch,
        # near or at the head of it.
        run: |
          git checkout "$(git branch --remote --contains "${GITHUB_REF}" | awk '$0!~/detached/{sub(/.+\//,"",$NF);print $NF;exit}')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.2
        with:
          title: "${{ env.VERSION }} Changelog Bump"
          body: "This is an automated changelog commit."
          commit-message: "chore: ${{ env.VERSION }} changelog bump"
          branch: "ready-${{ env.VERSION }}"
          signoff: "gh-actions"
      - name: QE Artifacts
        if: {{ env.PROD_RELEASE }}
        run: |
          performing production release tasks

