---
name: Prepare For Final
# This workflow triggers only on `rc` prerelease version tags. It creates a PR
# with an updated changelog.

on:
  push:
    tags:
      - v0.*-rc*

jobs:
  create:
    name: Prepare Final
    runs-on: 'ubuntu-latest'
    steps:
      - name: Versions
        run: |
          : "${tag:=${GITHUB_REF#refs/tags/}}"
          cat <<.
          ::set-env name=VERSION::${tag}
          ::set-env name=NEXT_VERSION::${tag%-rc*}
          .
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fix Checkout
        # A tag that triggers this workflow should only exist on one branch,
        # near or at the head of it.
        run: |
          git checkout "$(git branch --remote --contains "${GITHUB_REF}" | awk '$0!~/detached/{sub(/.+\//,"",$NF);print $NF;exit}')"
      - name: Changelog
        shell: bash
        run: |
          curl -o /tmp/git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64
          chmod u+x /tmp/git-chglog
          echo "creating change log for tag: ${NEXT_VERSION}"
          /tmp/git-chglog --next-tag "${NEXT_VERSION}" -o CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.1.2
        with:
          title: "${{ env.NEXT_VERSION }} Changelog Bump"
          body: "This is an automated changelog commit."
          commit-message: "chore: ${{ env.NEXT_VERSION }} changelog bump"
          branch: "ready-${{ env.NEXT_VERSION }}"
          signoff: "gh-actions"
