---
name: Release Actions

on:
  release:
    types: [published]

jobs:
  changelog-bump-pr:
    runs-on: 'ubuntu-latest'
    steps:
      # Build stuff happens here.
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
