---
name: Release Actions
# This action happens whenever a release is published.
#
# Because of the prepare-release workflow, this is triggered automatically
# on release candidate and release tags.

on:
  release:
    types: [published]

jobs:
  changelog-bump-pr:
    runs-on: 'ubuntu-latest'
    steps:
      # Build stuff happens here.
      - name: Checkout
        uses: actions/checkout@v2
