---
name: Release Actions

on:
  release:
    types: [published]

jobs:
  changelog-bump-pr:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - name: ChangeLogBump
        shell: bash
        run: |
          curl -o git-chglog -L https://github.com/git-chglog/git-chglog/releases/download/0.9.1/git-chglog_linux_amd64
          chmod u+x git-chglog
          ./git-chglog -o CHANGELOG.md
          rm -rf git-chglog
      - name: PullRequest
        uses: peter-evans/create-pull-request@v3.1.2
        with:
          title: "${{ github.ref }} Changelog Bump"
          body: "This is an automated change log bump following a release."
          commit-message: "cidi: ${{ github.ref }} changelog bump"
          branch: "${{github.ref}}-changelog-bump"
          signoff: "gh-actions"


          
